Repository team-essence/TAoSK-LP, pull requests merged in 2022-01, with the labels that each got.

#21 bugfix: フォルダ名を変更
  src/components/ui/carousel/Carousel.tsx
Labels: バグ, 優先度: 高

#23 feat: videoを追加 #22
  public/mp4/attack.mp4
  public/mp4/monster.mp4
  public/mp4/status.mp4
  src/@types/video.d.ts
  src/components/ui/modal/MobileStatusVisualizationModal.tsx
  src/components/ui/modal/MobileWorkVisualizationModal.tsx
  src/components/ui/modal/StatusVisualizationModal.tsx
  src/components/ui/modal/WorkVisualizationModal.tsx
  src/components/ui/spacer/Spacer.tsx
Labels: 機能追加, 優先度: 高

#25 fix: 開発モードのみgsapのmarkerを出す
  src/consts/scrollTrigger.ts
Labels: FIX

#29 add: ファーストビューのアニメーションをゲーム風に変更
  public/contents/background.svg
  public/contents/dot/about-taosk.svg
  public/contents/dot/concept.svg
  public/contents/dot/lets-start.svg
  public/contents/hovered-background.svg
  public/contents/illust/about-taosk.svg
  public/contents/illust/concept.svg
  public/contents/illust/lets-start.svg
  public/index.html
  public/screen/after.webp
  public/screen/before.webp
  public/screen/top-logo.webp
  src/View.tsx
  src/components/ui/header/FirstViewHeader.tsx
  src/components/ui/modal/HPandMPVisualizationModal.tsx
  src/components/ui/modal/MobileHPandMPVisualizationModal.tsx
  src/components/ui/modal/MobileStatusVisualizationModal.tsx
  src/components/ui/modal/MobileWorkVisualizationModal.tsx
  src/components/ui/modal/StatusVisualizationModal.tsx
  src/components/ui/modal/WorkVisualizationModal.tsx
  src/components/ui/spacer/Spacer.tsx
  src/components/ui/startTAoSK/StartTAoSK.tsx
  src/consts/aspect.ts
  src/consts/scrollTrigger.ts
  src/hooks/useAddFirstViewAnimation.ts
  src/hooks/useCalculateFirstViewAnimatedSize.ts
  src/hooks/useCalculateInnerPcStyle.ts
  src/hooks/useFirstViewBackgroundAnimation.ts
  src/hooks/useFirstViewInnerPcAnimation.ts
  src/hooks/useFirstViewLogoAndContentsAnimation.ts
  src/reportWebVitals.ts
  src/styles/global/theme.ts
  src/utils/color/convertIntoRGBA.ts
  src/utils/getFirstViewSizeRatio.ts
  src/utils/scrollAnimation.ts
Labels: 機能追加, FIX, 優先度: 高

#31 fix: iOS Safariでアニメーションが大きく崩れてしまう問題を修正
  src/components/ui/header/FirstViewHeader.tsx
  src/consts/scrollTrigger.ts
  src/hooks/useAddFirstViewAnimation.ts
  src/hooks/useFirstViewBackgroundAnimation.ts
  src/hooks/useFirstViewInnerPcAnimation.ts
  src/hooks/useFirstViewLogoAndContentsAnimation.ts
  src/utils/scrollAnimation.ts
Labels: バグ, FIX, 優先度: 高

#35 feat: youtube動画を埋め込む
  src/components/ui/videoArea/MobileVideoArea.tsx
  src/components/ui/videoArea/VideoArea.tsx
Labels: 機能追加

#36 fix: macでフルスクリーンにした時にアニメーションの計算がずれる問題の修正 #32
  src/hooks/useFirstViewBackgroundAnimation.ts
  src/hooks/useFirstViewInnerPcAnimation.ts
Labels: FIX, 改善

#34 add: 特徴セクションの文字/画像にアニメーションを付与
  src/components/ui/footer/SiteFooter.tsx
  src/components/ui/label/Feature.tsx
  src/components/ui/modal/HPandMPVisualizationModal.tsx
  src/components/ui/modal/MobileHPandMPVisualizationModal.tsx
  src/components/ui/modal/MobileStatusVisualizationModal.tsx
  src/components/ui/modal/MobileWorkVisualizationModal.tsx
  src/components/ui/modal/Modal.tsx
  src/components/ui/modal/StatusVisualizationModal.tsx
  src/components/ui/modal/WorkVisualizationModal.tsx
  src/components/ui/videoArea/MobileVideoArea.tsx
  src/styles/animation/modalAnimation.ts
  src/utils/figma/calculateSizeBasedOnFigma.ts
Labels: 改善

#38 feat: FaceAPIの動画を追加
  public/mp4/ar_face.mp4
  src/components/ui/modal/HPandMPVisualizationModal.tsx
  src/components/ui/modal/MobileHPandMPVisualizationModal.tsx
Labels: 機能追加

#41 fix: ファーストビューの画像をドラゴンありで差し替えた #40
  public/background/first_view.png
  public/index.html
Labels: FIX

#43 fix: YouTube動画のURLを変更
  src/components/ui/videoArea/MobileVideoArea.tsx
  src/components/ui/videoArea/VideoArea.tsx
Labels: FIX
